package wxj.ws.data;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-14T10:00:52.341+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://Data.ws.wxj/", name = "DataWs")
@XmlSeeAlso({ObjectFactory.class})
public interface DataWs {

    @WebMethod
    @RequestWrapper(localName = "getAllstudent", targetNamespace = "http://Data.ws.wxj/", className = "wxj.ws.data.GetAllstudent")
    @ResponseWrapper(localName = "getAllstudentResponse", targetNamespace = "http://Data.ws.wxj/", className = "wxj.ws.data.GetAllstudentResponse")
    @WebResult(name = "_return", targetNamespace = "")
    public wxj.ws.data.GetAllstudentResponse.Return getAllstudent();

    @WebMethod
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://Data.ws.wxj/", className = "wxj.ws.data.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://Data.ws.wxj/", className = "wxj.ws.data.AddStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        wxj.ws.data.Student arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://Data.ws.wxj/", className = "wxj.ws.data.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://Data.ws.wxj/", className = "wxj.ws.data.GetStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wxj.ws.data.Student> getStudent();

    @WebMethod
    @RequestWrapper(localName = "getStudentbyId", targetNamespace = "http://Data.ws.wxj/", className = "wxj.ws.data.GetStudentbyId")
    @ResponseWrapper(localName = "getStudentbyIdResponse", targetNamespace = "http://Data.ws.wxj/", className = "wxj.ws.data.GetStudentbyIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public wxj.ws.data.Student getStudentbyId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
