
package wxj.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWsImpleService", targetNamespace = "http://ws.wxj/", wsdlLocation = "http://192.168.1.109:8989/Server/hellows?wsdl")
public class HelloWsImpleService
    extends Service
{

    private final static URL HELLOWSIMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWSIMPLESERVICE_EXCEPTION;
    private final static QName HELLOWSIMPLESERVICE_QNAME = new QName("http://ws.wxj/", "HelloWsImpleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.109:8989/Server/hellows?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWSIMPLESERVICE_WSDL_LOCATION = url;
        HELLOWSIMPLESERVICE_EXCEPTION = e;
    }

    public HelloWsImpleService() {
        super(__getWsdlLocation(), HELLOWSIMPLESERVICE_QNAME);
    }

    public HelloWsImpleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWSIMPLESERVICE_QNAME, features);
    }

    public HelloWsImpleService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWSIMPLESERVICE_QNAME);
    }

    public HelloWsImpleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWSIMPLESERVICE_QNAME, features);
    }

    public HelloWsImpleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWsImpleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWsImple
     */
    @WebEndpoint(name = "HelloWsImplePort")
    public HelloWsImple getHelloWsImplePort() {
        return super.getPort(new QName("http://ws.wxj/", "HelloWsImplePort"), HelloWsImple.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWsImple
     */
    @WebEndpoint(name = "HelloWsImplePort")
    public HelloWsImple getHelloWsImplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wxj/", "HelloWsImplePort"), HelloWsImple.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWSIMPLESERVICE_EXCEPTION!= null) {
            throw HELLOWSIMPLESERVICE_EXCEPTION;
        }
        return HELLOWSIMPLESERVICE_WSDL_LOCATION;
    }

}
