package wxj.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-13T17:55:11.813+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "HelloWsImpleService",
                  wsdlLocation = "http://10.28.190.164:8080/Server_CXF/hellows?wsdl",
                  targetNamespace = "http://ws.wxj/")
public class HelloWsImpleService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.wxj/", "HelloWsImpleService");
    public final static QName HelloWsImplePort = new QName("http://ws.wxj/", "HelloWsImplePort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.28.190.164:8080/Server_CXF/hellows?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWsImpleService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.28.190.164:8080/Server_CXF/hellows?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWsImpleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWsImpleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWsImpleService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloWsImpleService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWsImpleService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWsImpleService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloWsImple
     */
    @WebEndpoint(name = "HelloWsImplePort")
    public HelloWsImple getHelloWsImplePort() {
        return super.getPort(HelloWsImplePort, HelloWsImple.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWsImple
     */
    @WebEndpoint(name = "HelloWsImplePort")
    public HelloWsImple getHelloWsImplePort(WebServiceFeature... features) {
        return super.getPort(HelloWsImplePort, HelloWsImple.class, features);
    }

}
