package wxj.ws.cxf.spring.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-16T10:39:09.722+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://ws.spring.cxf.ws.wxj/", name = "OrderWs")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderWs {

    @WebMethod
    @RequestWrapper(localName = "getOrderbyId", targetNamespace = "http://ws.spring.cxf.ws.wxj/", className = "wxj.ws.cxf.spring.ws.GetOrderbyId")
    @ResponseWrapper(localName = "getOrderbyIdResponse", targetNamespace = "http://ws.spring.cxf.ws.wxj/", className = "wxj.ws.cxf.spring.ws.GetOrderbyIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public wxj.ws.cxf.spring.ws.Order getOrderbyId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
