package wxj.ws.cxf.spring.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-16T10:39:09.755+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "OrderImpleService",
                  wsdlLocation = "http://localhost:8080/Server_CXF_Spring/orderws?wsdl",
                  targetNamespace = "http://ws.spring.cxf.ws.wxj/")
public class OrderImpleService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.spring.cxf.ws.wxj/", "OrderImpleService");
    public final static QName OrderImplePort = new QName("http://ws.spring.cxf.ws.wxj/", "OrderImplePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Server_CXF_Spring/orderws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderImpleService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Server_CXF_Spring/orderws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderImpleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderImpleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderImpleService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OrderImpleService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrderImpleService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrderImpleService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OrderWs
     */
    @WebEndpoint(name = "OrderImplePort")
    public OrderWs getOrderImplePort() {
        return super.getPort(OrderImplePort, OrderWs.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderWs
     */
    @WebEndpoint(name = "OrderImplePort")
    public OrderWs getOrderImplePort(WebServiceFeature... features) {
        return super.getPort(OrderImplePort, OrderWs.class, features);
    }

}
